spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ohsoontaxi
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #show_sql: true
        format_sql: ture

aws:
  access-key:
  secret-key:
  s3:
    bucket: test
    base-url: test

auth:
  jwt:
    secretKey: 7JWI64WV7ZWY64uk7KCQ7J6Q7YSM7JqULg==
    accessExp: 1800
    refreshExp: 50400
    header: Authorization
    prefix: Bearer

logging.level:
  org.hibernate.SQL: debug